package generator

import (
	"bufio"
	"fmt"
	"os"
	"soliton/pkg/metadata"
	"strings"
)

// EntityGenerator Entity 接口实现生成器
//
// 为每个聚合根自动生成 Entity 接口的实现方法：
//   - GetID() int64

//   - SetID(id int64)
//   - IsNew() bool
//
// 生成策略：直接追加到聚合根文件末尾（充血模型）
type EntityGenerator struct{}

// NewEntityGenerator 创建 Entity 生成器
func NewEntityGenerator() *EntityGenerator {
	return &EntityGenerator{}
}

// Generate 为聚合根生成 Entity 接口实现（追加到原文件）
func (g *EntityGenerator) Generate(agg *metadata.AggregateMetadata) error {
	// 读取原文件内容
	content, err := g.readFile(agg.FilePath)
	if err != nil {
		return fmt.Errorf("读取文件失败: %w", err)
	}

	// 移除旧的生成代码（如果存在）
	content = g.removeGeneratedCode(content)

	// 生成新的 Entity 方法代码
	generatedCode := g.generateEntityMethods(agg)

	// 追加到文件末尾
	finalContent := content + "\n" + generatedCode

	// 写回文件
	if err := g.writeFile(agg.FilePath, finalContent); err != nil {
		return fmt.Errorf("写入文件失败: %w", err)
	}

	fmt.Printf("✅ 已为 %s 生成 Entity 方法\n", agg.Name)
	return nil
}

// readFile 读取文件内容
func (g *EntityGenerator) readFile(filePath string) (string, error) {
	file, err := os.Open(filePath)
	if err != nil {
		return "", err
	}
	defer file.Close()

	var sb strings.Builder
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		sb.WriteString(scanner.Text())
		sb.WriteString("\n")
	}

	if err := scanner.Err(); err != nil {
		return "", err
	}

	return sb.String(), nil
}

// writeFile 写入文件
func (g *EntityGenerator) writeFile(filePath string, content string) error {
	return os.WriteFile(filePath, []byte(content), 0644)
}

// removeGeneratedCode 移除旧的生成代码
func (g *EntityGenerator) removeGeneratedCode(content string) string {
	marker := "// ========== 以下代码由 soliton 自动生成，请勿手动修改 =========="

	// 查找分隔标记
	if idx := strings.Index(content, marker); idx != -1 {
		// 删除标记及其之后的所有内容
		content = content[:idx]
		// 移除末尾多余的空行
		content = strings.TrimRight(content, "\n")
	}

	return content
}

// generateEntityMethods 生成 Entity 接口实现代码
func (g *EntityGenerator) generateEntityMethods(agg *metadata.AggregateMetadata) string {
	var sb strings.Builder

	// 分隔标记
	sb.WriteString("// ========== 以下代码由 soliton 自动生成，请勿手动修改 ==========\n")
	sb.WriteString("// Code generated by soliton. DO NOT EDIT.\n\n")

	// 确定 ID 字段名称和类型
	idFieldName := "ID"
	idFieldType := "int64"
	if agg.IDField != nil {
		idFieldName = agg.IDField.Name
		idFieldType = agg.IDField.Type
	}

	// 接收者名称（聚合根名称首字母小写）
	receiver := strings.ToLower(string(agg.Name[0]))

	// GetID 方法
	sb.WriteString("// GetID 获取实体ID\n")
	sb.WriteString(fmt.Sprintf("func (%s *%s) GetID() int64 {\n", receiver, agg.Name))
	if idFieldType == "int64" {
		sb.WriteString(fmt.Sprintf("\treturn %s.%s\n", receiver, idFieldName))
	} else {
		// 如果 ID 字段不是 int64，需要类型转换
		sb.WriteString(fmt.Sprintf("\treturn int64(%s.%s)\n", receiver, idFieldName))
	}
	sb.WriteString("}\n\n")

	// SetID 方法
	sb.WriteString("// SetID 设置实体ID\n")
	sb.WriteString(fmt.Sprintf("func (%s *%s) SetID(id int64) {\n", receiver, agg.Name))
	if idFieldType == "int64" {
		sb.WriteString(fmt.Sprintf("\t%s.%s = id\n", receiver, idFieldName))
	} else {
		// 如果 ID 字段不是 int64，需要类型转换
		sb.WriteString(fmt.Sprintf("\t%s.%s = %s(id)\n", receiver, idFieldName, idFieldType))
	}
	sb.WriteString("}\n\n")

	// IsNew 方法
	sb.WriteString("// IsNew 判断是否为新实体\n")
	sb.WriteString(fmt.Sprintf("func (%s *%s) IsNew() bool {\n", receiver, agg.Name))
	sb.WriteString(fmt.Sprintf("\treturn %s.%s == 0\n", receiver, idFieldName))
	sb.WriteString("}\n")

	return sb.String()
}
