package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"soliton/pkg/metadata"
	"strings"
)

// EntityGenerator Entity 接口实现生成器
//
// 为每个聚合根自动生成 Entity 接口的实现方法：
//   - GetID() int64
//   - SetID(id int64)
//   - IsNew() bool
//
// 生成文件：domain/model/{AggregateName}_entity.go
type EntityGenerator struct{}

// NewEntityGenerator 创建 Entity 生成器
func NewEntityGenerator() *EntityGenerator {
	return &EntityGenerator{}
}

// Generate 为聚合根生成 Entity 接口实现
func (g *EntityGenerator) Generate(agg *metadata.AggregateMetadata, outputDir string) error {
	// 确保输出目录存在
	if err := os.MkdirAll(outputDir, 0755); err != nil {
		return fmt.Errorf("创建输出目录失败: %w", err)
	}

	// 生成文件路径
	fileName := fmt.Sprintf("%s_entity.go", toLowerFirst(agg.Name))
	filePath := filepath.Join(outputDir, fileName)

	// 生成代码
	code := g.generateCode(agg)

	// 写入文件
	if err := os.WriteFile(filePath, []byte(code), 0644); err != nil {
		return fmt.Errorf("写入文件失败: %w", err)
	}

	return nil
}

// generateCode 生成 Entity 接口实现代码
func (g *EntityGenerator) generateCode(agg *metadata.AggregateMetadata) string {
	var sb strings.Builder

	// 文件头
	sb.WriteString(fmt.Sprintf("// Code generated by soliton. DO NOT EDIT.\n\n"))
	sb.WriteString(fmt.Sprintf("package %s\n\n", agg.PackageName))

	// 确定 ID 字段名称和类型
	idFieldName := "ID"
	idFieldType := "int64"
	if agg.IDField != nil {
		idFieldName = agg.IDField.Name
		idFieldType = agg.IDField.Type
	}

	// 接收者名称（聚合根名称首字母小写）
	receiver := strings.ToLower(string(agg.Name[0]))

	// GetID 方法
	sb.WriteString(fmt.Sprintf("// GetID 获取实体ID\n"))
	sb.WriteString(fmt.Sprintf("func (%s *%s) GetID() int64 {\n", receiver, agg.Name))
	if idFieldType == "int64" {
		sb.WriteString(fmt.Sprintf("\treturn %s.%s\n", receiver, idFieldName))
	} else {
		// 如果 ID 字段不是 int64，需要类型转换
		sb.WriteString(fmt.Sprintf("\treturn int64(%s.%s)\n", receiver, idFieldName))
	}
	sb.WriteString("}\n\n")

	// SetID 方法
	sb.WriteString(fmt.Sprintf("// SetID 设置实体ID\n"))
	sb.WriteString(fmt.Sprintf("func (%s *%s) SetID(id int64) {\n", receiver, agg.Name))
	if idFieldType == "int64" {
		sb.WriteString(fmt.Sprintf("\t%s.%s = id\n", receiver, idFieldName))
	} else {
		// 如果 ID 字段不是 int64，需要类型转换
		sb.WriteString(fmt.Sprintf("\t%s.%s = %s(id)\n", receiver, idFieldName, idFieldType))
	}
	sb.WriteString("}\n\n")

	// IsNew 方法
	sb.WriteString(fmt.Sprintf("// IsNew 判断是否为新实体\n"))
	sb.WriteString(fmt.Sprintf("func (%s *%s) IsNew() bool {\n", receiver, agg.Name))
	sb.WriteString(fmt.Sprintf("\treturn %s.%s == 0\n", receiver, idFieldName))
	sb.WriteString("}\n")

	return sb.String()
}

// toLowerFirst 将字符串首字母转为小写
func toLowerFirst(s string) string {
	if len(s) == 0 {
		return s
	}
	return strings.ToLower(string(s[0])) + s[1:]
}
