package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"soliton/pkg/metadata"
	"strings"
)

// ServiceImplGenerator 领域服务实现生成器
//
// 生成嵌入 BaseService[T] 的具体服务实现，包含标记驱动的校验逻辑：
//   - required：非空校验
//   - unique：唯一性校验
//   - ref：外键存在性校验
//   - enum：枚举值校验
//
// 生成文件：domain/service/impl/{AggregateName}ServiceImpl.go
type ServiceImplGenerator struct{}

// NewServiceImplGenerator 创建领域服务实现生成器
func NewServiceImplGenerator() *ServiceImplGenerator {
	return &ServiceImplGenerator{}
}

// Generate 为聚合根生成领域服务实现
func (g *ServiceImplGenerator) Generate(agg *metadata.AggregateMetadata, outputDir string) error {
	// 创建输出目录：service/impl
	implDir := filepath.Join(outputDir, "service", "impl")
	if err := os.MkdirAll(implDir, 0755); err != nil {
		return fmt.Errorf("创建输出目录失败: %w", err)
	}

	// 生成文件路径
	fileName := fmt.Sprintf("%sServiceImpl.go", agg.Name)
	filePath := filepath.Join(implDir, fileName)

	// 生成代码
	code := g.generateCode(agg)

	// 写入文件
	if err := os.WriteFile(filePath, []byte(code), 0644); err != nil {
		return fmt.Errorf("写入文件失败: %w", err)
	}

	return nil
}

// generateCode 生成领域服务实现代码
func (g *ServiceImplGenerator) generateCode(agg *metadata.AggregateMetadata) string {
	var sb strings.Builder

	// 文件头
	sb.WriteString("// Code generated by soliton. DO NOT EDIT.\n\n")
	sb.WriteString("package impl\n\n")

	// 导入
	sb.WriteString("import (\n")
	sb.WriteString("\t\"context\"\n")
	sb.WriteString("\t\"errors\"\n")
	sb.WriteString("\t\"fmt\"\n")
	sb.WriteString("\t\"model\"\n")
	sb.WriteString("\t\"repository\"\n")
	sb.WriteString("\t\"soliton/pkg/framework\"\n")
	sb.WriteString(")\n\n")

	// 结构体定义
	sb.WriteString(fmt.Sprintf("// %sServiceImpl %s 领域服务实现\n", agg.Name, agg.Name))
	sb.WriteString(fmt.Sprintf("type %sServiceImpl struct {\n", agg.Name))
	sb.WriteString(fmt.Sprintf("\tframework.BaseService[model.%s]\n", agg.Name))
	sb.WriteString(fmt.Sprintf("\trepository repository.%sRepository\n", agg.Name))
	sb.WriteString("}\n\n")

	// 构造函数
	sb.WriteString(g.generateConstructor(agg))
	sb.WriteString("\n")

	// 重写 Add 方法（含校验）
	sb.WriteString(g.generateAddMethod(agg))
	sb.WriteString("\n")

	// 重写 Update 方法（含校验）
	sb.WriteString(g.generateUpdateMethod(agg))
	sb.WriteString("\n")

	// 生成校验方法
	sb.WriteString(g.generateValidationMethods(agg))

	return sb.String()
}

// generateConstructor 生成构造函数
func (g *ServiceImplGenerator) generateConstructor(agg *metadata.AggregateMetadata) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("// New%sService 创建 %s 领域服务实例\n", agg.Name, agg.Name))
	sb.WriteString(fmt.Sprintf("func New%sService(repo repository.%sRepository) *%sServiceImpl {\n",
		agg.Name, agg.Name, agg.Name))
	sb.WriteString(fmt.Sprintf("\treturn &%sServiceImpl{\n", agg.Name))
	sb.WriteString(fmt.Sprintf("\t\tBaseService: *framework.NewBaseService[model.%s](repo),\n", agg.Name))
	sb.WriteString("\t\trepository:  repo,\n")
	sb.WriteString("\t}\n")
	sb.WriteString("}\n")

	return sb.String()
}

// generateAddMethod 生成 Add 方法（含校验）
func (g *ServiceImplGenerator) generateAddMethod(agg *metadata.AggregateMetadata) string {
	var sb strings.Builder

	receiver := strings.ToLower(string(agg.Name[0]))

	sb.WriteString(fmt.Sprintf("// Add 添加实体（含校验）\n"))
	sb.WriteString(fmt.Sprintf("func (%s *%sServiceImpl) Add(ctx context.Context, entity *model.%s) error {\n",
		receiver, agg.Name, agg.Name))

	// 生成校验逻辑
	sb.WriteString("\t// 必填字段校验\n")
	sb.WriteString(fmt.Sprintf("\tif err := %s.validateRequired(entity); err != nil {\n", receiver))
	sb.WriteString("\t\treturn err\n")
	sb.WriteString("\t}\n\n")

	sb.WriteString("\t// 唯一性校验\n")
	sb.WriteString(fmt.Sprintf("\tif err := %s.validateUnique(ctx, entity); err != nil {\n", receiver))
	sb.WriteString("\t\treturn err\n")
	sb.WriteString("\t}\n\n")

	sb.WriteString("\t// 枚举值校验\n")
	sb.WriteString(fmt.Sprintf("\tif err := %s.validateEnum(entity); err != nil {\n", receiver))
	sb.WriteString("\t\treturn err\n")
	sb.WriteString("\t}\n\n")

	sb.WriteString("\t// 调用仓储层保存\n")
	sb.WriteString(fmt.Sprintf("\treturn %s.repository.Add(ctx, entity)\n", receiver))
	sb.WriteString("}\n")

	return sb.String()
}

// generateUpdateMethod 生成 Update 方法（含校验）
func (g *ServiceImplGenerator) generateUpdateMethod(agg *metadata.AggregateMetadata) string {
	var sb strings.Builder

	receiver := strings.ToLower(string(agg.Name[0]))

	sb.WriteString(fmt.Sprintf("// Update 更新实体（含校验）\n"))
	sb.WriteString(fmt.Sprintf("func (%s *%sServiceImpl) Update(ctx context.Context, entity *model.%s) error {\n",
		receiver, agg.Name, agg.Name))

	sb.WriteString("\t// 必填字段校验\n")
	sb.WriteString(fmt.Sprintf("\tif err := %s.validateRequired(entity); err != nil {\n", receiver))
	sb.WriteString("\t\treturn err\n")
	sb.WriteString("\t}\n\n")

	sb.WriteString("\t// 唯一性校验（排除自己）\n")
	sb.WriteString(fmt.Sprintf("\tif err := %s.validateUniqueExcludeSelf(ctx, entity); err != nil {\n", receiver))
	sb.WriteString("\t\treturn err\n")
	sb.WriteString("\t}\n\n")

	sb.WriteString("\t// 枚举值校验\n")
	sb.WriteString(fmt.Sprintf("\tif err := %s.validateEnum(entity); err != nil {\n", receiver))
	sb.WriteString("\t\treturn err\n")
	sb.WriteString("\t}\n\n")

	sb.WriteString("\t// 调用仓储层更新\n")
	sb.WriteString(fmt.Sprintf("\treturn %s.repository.Update(ctx, entity)\n", receiver))
	sb.WriteString("}\n")

	return sb.String()
}

// generateValidationMethods 生成校验方法
func (g *ServiceImplGenerator) generateValidationMethods(agg *metadata.AggregateMetadata) string {
	var sb strings.Builder

	receiver := strings.ToLower(string(agg.Name[0]))

	// 1. 必填字段校验
	sb.WriteString(fmt.Sprintf("// validateRequired 必填字段校验\n"))
	sb.WriteString(fmt.Sprintf("func (%s *%sServiceImpl) validateRequired(entity *model.%s) error {\n",
		receiver, agg.Name, agg.Name))

	hasRequired := false
	for _, field := range agg.Fields {
		if field.Annotations.IsRequired {
			hasRequired = true
			// 根据类型生成不同的校验逻辑
			if field.Type == "string" {
				sb.WriteString(fmt.Sprintf("\tif entity.%s == \"\" {\n", field.Name))
				sb.WriteString(fmt.Sprintf("\t\treturn errors.New(\"%s 不能为空\")\n", field.Name))
				sb.WriteString("\t}\n")
			} else if !field.IsPointer {
				sb.WriteString(fmt.Sprintf("\tif entity.%s == 0 {\n", field.Name))
				sb.WriteString(fmt.Sprintf("\t\treturn errors.New(\"%s 不能为空\")\n", field.Name))
				sb.WriteString("\t}\n")
			}
		}
	}

	if !hasRequired {
		sb.WriteString("\t// 无必填字段\n")
	}

	sb.WriteString("\treturn nil\n")
	sb.WriteString("}\n\n")

	// 2. 唯一性校验
	sb.WriteString(fmt.Sprintf("// validateUnique 唯一性校验\n"))
	sb.WriteString(fmt.Sprintf("func (%s *%sServiceImpl) validateUnique(ctx context.Context, entity *model.%s) error {\n",
		receiver, agg.Name, agg.Name))

	hasUnique := false
	for _, field := range agg.Fields {
		if field.Annotations.IsUnique {
			hasUnique = true
			sb.WriteString(fmt.Sprintf("\t// %s 唯一性校验\n", field.Name))
			sb.WriteString(fmt.Sprintf("\texisting, err := %s.repository.GetBy%s(ctx, entity.%s)\n",
				receiver, field.Name, field.Name))
			sb.WriteString("\tif err == nil && existing != nil {\n")
			sb.WriteString(fmt.Sprintf("\t\treturn fmt.Errorf(\"%s 已存在: %%v\", entity.%s)\n",
				field.Name, field.Name))
			sb.WriteString("\t}\n\n")
		}
	}

	if !hasUnique {
		sb.WriteString("\t// 无唯一字段\n")
	}

	sb.WriteString("\treturn nil\n")
	sb.WriteString("}\n\n")

	// 3. 唯一性校验（排除自己）
	sb.WriteString(fmt.Sprintf("// validateUniqueExcludeSelf 唯一性校验（排除自己）\n"))
	sb.WriteString(fmt.Sprintf("func (%s *%sServiceImpl) validateUniqueExcludeSelf(ctx context.Context, entity *model.%s) error {\n",
		receiver, agg.Name, agg.Name))

	if hasUnique {
		for _, field := range agg.Fields {
			if field.Annotations.IsUnique {
				sb.WriteString(fmt.Sprintf("\t// %s 唯一性校验\n", field.Name))
				sb.WriteString(fmt.Sprintf("\texisting, err := %s.repository.GetBy%s(ctx, entity.%s)\n",
					receiver, field.Name, field.Name))
				sb.WriteString("\tif err == nil && existing != nil && existing.GetID() != entity.GetID() {\n")
				sb.WriteString(fmt.Sprintf("\t\treturn fmt.Errorf(\"%s 已存在: %%v\", entity.%s)\n",
					field.Name, field.Name))
				sb.WriteString("\t}\n\n")
			}
		}
	} else {
		sb.WriteString("\t// 无唯一字段\n")
	}

	sb.WriteString("\treturn nil\n")
	sb.WriteString("}\n\n")

	// 4. 枚举值校验
	sb.WriteString(fmt.Sprintf("// validateEnum 枚举值校验\n"))
	sb.WriteString(fmt.Sprintf("func (%s *%sServiceImpl) validateEnum(entity *model.%s) error {\n",
		receiver, agg.Name, agg.Name))

	hasEnum := false
	for _, field := range agg.Fields {
		if len(field.Annotations.EnumValues) > 0 {
			hasEnum = true
			sb.WriteString(fmt.Sprintf("\t// %s 枚举校验\n", field.Name))
			sb.WriteString(fmt.Sprintf("\tvalid%s := map[string]bool{\n", field.Name))
			for _, value := range field.Annotations.EnumValues {
				sb.WriteString(fmt.Sprintf("\t\t\"%s\": true,\n", value))
			}
			sb.WriteString("\t}\n")
			sb.WriteString(fmt.Sprintf("\tif !valid%s[entity.%s] {\n", field.Name, field.Name))
			sb.WriteString(fmt.Sprintf("\t\treturn fmt.Errorf(\"%s 值无效: %%s\", entity.%s)\n",
				field.Name, field.Name))
			sb.WriteString("\t}\n\n")
		}
	}

	if !hasEnum {
		sb.WriteString("\t// 无枚举字段\n")
	}

	sb.WriteString("\treturn nil\n")
	sb.WriteString("}\n\n")

	return sb.String()
}
