package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"soliton/pkg/metadata"
	"strings"
)

// ServiceInterfaceGenerator 领域服务接口生成器
//
// 生成继承泛型 Service[T] 的具体领域服务接口。
//
// 生成文件：domain/service/{AggregateName}Service.go
type ServiceInterfaceGenerator struct{}

// NewServiceInterfaceGenerator 创建领域服务接口生成器
func NewServiceInterfaceGenerator() *ServiceInterfaceGenerator {
	return &ServiceInterfaceGenerator{}
}

// Generate 为聚合根生成领域服务接口
func (g *ServiceInterfaceGenerator) Generate(agg *metadata.AggregateMetadata, outputDir string) error {
	// 创建输出目录
	serviceDir := filepath.Join(outputDir, "modelservice")
	if err := os.MkdirAll(serviceDir, 0755); err != nil {
		return fmt.Errorf("创建输出目录失败: %w", err)
	}

	// 生成文件路径
	fileName := fmt.Sprintf("%sService.go", agg.Name)
	filePath := filepath.Join(serviceDir, fileName)

	// 生成代码
	code := g.generateCode(agg)

	// 写入文件
	if err := os.WriteFile(filePath, []byte(code), 0644); err != nil {
		return fmt.Errorf("写入文件失败: %w", err)
	}

	return nil
}

// generateCode 生成领域服务接口代码
func (g *ServiceInterfaceGenerator) generateCode(agg *metadata.AggregateMetadata) string {
	var sb strings.Builder

	// 文件头
	sb.WriteString("// Code generated by soliton. DO NOT EDIT.\n\n")
	sb.WriteString("package modelservice\n\n")

	// 导入
	sb.WriteString("import (\n")
	sb.WriteString("\t\"model\"\n")
	sb.WriteString("\t\"soliton/pkg/framework\"\n")
	sb.WriteString(")\n\n")

	// 接口定义
	sb.WriteString(fmt.Sprintf("// %sService %s 领域服务接口\n", agg.Name, agg.Name))
	sb.WriteString(fmt.Sprintf("type %sService interface {\n", agg.Name))

	// 继承泛型接口
	sb.WriteString(fmt.Sprintf("\tframework.Service[model.%s]\n", agg.Name))

	// 可以在这里添加扩展业务方法的注释提示
	sb.WriteString("\n")
	sb.WriteString("\t// 在此处添加扩展业务方法\n")
	sb.WriteString("\t// 例如：PlaceOrder(ctx context.Context, order *model.Order) error\n")

	sb.WriteString("}\n")

	return sb.String()
}
